services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      # These map your .env variables to the Docker image specific variables
      POSTGRES_USER: ${DB_USERNAME:-username}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-maind_controllers}
    ports:
      # Maps localhost:5432 to container:5432
      - "${DB_PORT:-5432}:5432"
    volumes:
      # Persist data even if container is removed
      - postgres_data:/var/lib/postgresql/data
  chroma_db:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    ports:
      - "8000:8000"   # host:container
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - IS_PERSISTENT=TRUE
      - CHROMA_DB_IMPL=sqlite
      - PERSIST_DIRECTORY=/chroma/data    
    volumes:
      - ./chroma_data:/chroma/data        
  backend:
    build: ./backend
    container_name: backend
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/backend
    depends_on:
      - db
      - chroma_db

      
volumes:
  postgres_data: